<a href="https://colab.research.google.com/github/itsyogi01/PYTHON--45DAYS-PRACTICE/blob/main/day9_numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# np.sort
import numpy as np
a = np.random.randint(1,100,50)
a

array([72, 71, 37, 56, 73, 96, 75, 12, 82, 41, 60, 61, 63, 60,  6, 83, 85,
       18, 33, 62, 72, 78, 72,  3, 96, 25, 95, 25, 15, 48, 61, 54, 93, 30,
       48, 34, 56,  7, 54, 23, 79, 62, 70,  1, 24, 20, 62, 94,  3, 18])

In [2]:
np.sort(a)

array([ 1,  3,  3,  6,  7, 12, 15, 18, 18, 20, 23, 24, 25, 25, 30, 33, 34,
       37, 41, 48, 48, 54, 54, 56, 56, 60, 60, 61, 61, 62, 62, 62, 63, 70,
       71, 72, 72, 72, 73, 75, 78, 79, 82, 83, 85, 93, 94, 95, 96, 96])

In [7]:
b = np.random.randint(1,100,50).reshape(5,10)
b


array([[64, 16, 19, 21, 29, 53,  6, 28, 65, 71],
       [ 4,  5, 63, 12, 48, 76, 12, 71, 63, 62],
       [ 8, 31, 82, 78, 90,  2, 36,  6, 55, 87],
       [16, 75,  1, 55, 99, 84, 20, 73, 73, 41],
       [77, 79, 43, 91, 99, 55, 97, 84, 80, 51]])

In [9]:
np.sort(b,axis = 0)

array([[ 4,  5,  1, 12, 29,  2,  6,  6, 55, 41],
       [ 8, 16, 19, 21, 48, 53, 12, 28, 63, 51],
       [16, 31, 43, 55, 90, 55, 20, 71, 65, 62],
       [64, 75, 63, 78, 99, 76, 36, 73, 73, 71],
       [77, 79, 82, 91, 99, 84, 97, 84, 80, 87]])

In [10]:
np.sort(b, axis = 1)

array([[ 6, 16, 19, 21, 28, 29, 53, 64, 65, 71],
       [ 4,  5, 12, 12, 48, 62, 63, 63, 71, 76],
       [ 2,  6,  8, 31, 36, 55, 78, 82, 87, 90],
       [ 1, 16, 20, 41, 55, 73, 73, 75, 84, 99],
       [43, 51, 55, 77, 79, 80, 84, 91, 97, 99]])

In [11]:
np.sort(a)[::-1]

array([96, 96, 95, 94, 93, 85, 83, 82, 79, 78, 75, 73, 72, 72, 72, 71, 70,
       63, 62, 62, 62, 61, 61, 60, 60, 56, 56, 54, 54, 48, 48, 41, 37, 34,
       33, 30, 25, 25, 24, 23, 20, 18, 18, 15, 12,  7,  6,  3,  3,  1])

In [12]:
np.sort(b)[::-1]

array([[43, 51, 55, 77, 79, 80, 84, 91, 97, 99],
       [ 1, 16, 20, 41, 55, 73, 73, 75, 84, 99],
       [ 2,  6,  8, 31, 36, 55, 78, 82, 87, 90],
       [ 4,  5, 12, 12, 48, 62, 63, 63, 71, 76],
       [ 6, 16, 19, 21, 28, 29, 53, 64, 65, 71]])

In [13]:
# ==========np.append==============
a

array([72, 71, 37, 56, 73, 96, 75, 12, 82, 41, 60, 61, 63, 60,  6, 83, 85,
       18, 33, 62, 72, 78, 72,  3, 96, 25, 95, 25, 15, 48, 61, 54, 93, 30,
       48, 34, 56,  7, 54, 23, 79, 62, 70,  1, 24, 20, 62, 94,  3, 18])

In [14]:
np.append(a,200)

array([ 72,  71,  37,  56,  73,  96,  75,  12,  82,  41,  60,  61,  63,
        60,   6,  83,  85,  18,  33,  62,  72,  78,  72,   3,  96,  25,
        95,  25,  15,  48,  61,  54,  93,  30,  48,  34,  56,   7,  54,
        23,  79,  62,  70,   1,  24,  20,  62,  94,   3,  18, 200])

In [15]:
b

array([[64, 16, 19, 21, 29, 53,  6, 28, 65, 71],
       [ 4,  5, 63, 12, 48, 76, 12, 71, 63, 62],
       [ 8, 31, 82, 78, 90,  2, 36,  6, 55, 87],
       [16, 75,  1, 55, 99, 84, 20, 73, 73, 41],
       [77, 79, 43, 91, 99, 55, 97, 84, 80, 51]])

In [17]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[64., 16., 19., 21., 29., 53.,  6., 28., 65., 71.,  1.],
       [ 4.,  5., 63., 12., 48., 76., 12., 71., 63., 62.,  1.],
       [ 8., 31., 82., 78., 90.,  2., 36.,  6., 55., 87.,  1.],
       [16., 75.,  1., 55., 99., 84., 20., 73., 73., 41.,  1.],
       [77., 79., 43., 91., 99., 55., 97., 84., 80., 51.,  1.]])

In [20]:
np.append(b,np.random.random((b.shape[0],1)),axis = 1)

array([[64.        , 16.        , 19.        , 21.        , 29.        ,
        53.        ,  6.        , 28.        , 65.        , 71.        ,
         0.92215762],
       [ 4.        ,  5.        , 63.        , 12.        , 48.        ,
        76.        , 12.        , 71.        , 63.        , 62.        ,
         0.78053928],
       [ 8.        , 31.        , 82.        , 78.        , 90.        ,
         2.        , 36.        ,  6.        , 55.        , 87.        ,
         0.22686791],
       [16.        , 75.        ,  1.        , 55.        , 99.        ,
        84.        , 20.        , 73.        , 73.        , 41.        ,
         0.69541972],
       [77.        , 79.        , 43.        , 91.        , 99.        ,
        55.        , 97.        , 84.        , 80.        , 51.        ,
         0.88789861]])

In [26]:
# np.concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(6).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d),axis=0)


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [27]:
c = np.arange(6).reshape(2,3)
d = np.arange(6).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d),axis=1)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [29]:
# ================np.unique==============
a = np.array([1,1,2,2,3,3,4,4,5,5,7,10])
np.unique(a)

array([ 1,  2,  3,  4,  5,  7, 10])

In [37]:
# =================np.expend_dims==========print
print(a)
print(a.shape)

[ 1  1  2  2  3  3  4  4  5  5  7 10]
(12,)


In [40]:
print(np.expand_dims(a,axis = 0))
np.expand_dims(a,axis = 0).shape

[[ 1  1  2  2  3  3  4  4  5  5  7 10]]


(1, 12)

In [41]:
np.expand_dims(a,axis = 1)

array([[ 1],
       [ 1],
       [ 2],
       [ 2],
       [ 3],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 5],
       [ 7],
       [10]])

In [42]:
# ==================np.where===============
a


array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  7, 10])

In [49]:
np.where(a>7)

(array([11]),)

In [50]:
np.where(a==5,0,a)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  0,  0,  7, 10])

In [51]:
np.where(a%2==0,100,a)

array([  1,   1, 100, 100,   3,   3, 100, 100,   5,   5,   7, 100])

In [52]:
# =====================np.argmax==================
a

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  7, 10])

In [53]:
np.argmax(a)

np.int64(11)

In [54]:
b

array([[64, 16, 19, 21, 29, 53,  6, 28, 65, 71],
       [ 4,  5, 63, 12, 48, 76, 12, 71, 63, 62],
       [ 8, 31, 82, 78, 90,  2, 36,  6, 55, 87],
       [16, 75,  1, 55, 99, 84, 20, 73, 73, 41],
       [77, 79, 43, 91, 99, 55, 97, 84, 80, 51]])

In [55]:
np.argmax(b,axis =0)

array([4, 4, 2, 4, 3, 3, 4, 4, 4, 2])

In [56]:
np.argmax(b,axis =1)

array([9, 5, 4, 4, 4])

In [57]:
a

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  7, 10])

In [58]:
np.argmin(a)

np.int64(0)

In [59]:
# ===================np.cumsum============
a

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  7, 10])

In [60]:
np.cumsum(a)

array([ 1,  2,  4,  6,  9, 12, 16, 20, 25, 30, 37, 47])

In [61]:
b

array([[64, 16, 19, 21, 29, 53,  6, 28, 65, 71],
       [ 4,  5, 63, 12, 48, 76, 12, 71, 63, 62],
       [ 8, 31, 82, 78, 90,  2, 36,  6, 55, 87],
       [16, 75,  1, 55, 99, 84, 20, 73, 73, 41],
       [77, 79, 43, 91, 99, 55, 97, 84, 80, 51]])

In [63]:
np.cumsum(b ,axis = 1)

array([[ 64,  80,  99, 120, 149, 202, 208, 236, 301, 372],
       [  4,   9,  72,  84, 132, 208, 220, 291, 354, 416],
       [  8,  39, 121, 199, 289, 291, 327, 333, 388, 475],
       [ 16,  91,  92, 147, 246, 330, 350, 423, 496, 537],
       [ 77, 156, 199, 290, 389, 444, 541, 625, 705, 756]])

In [64]:
# ======================cumprod================
a

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  7, 10])

In [65]:
np.cumprod(a)

array([      1,       1,       2,       4,      12,      36,     144,
           576,    2880,   14400,  100800, 1008000])

In [66]:
# ==========================np.percentile======================
a

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  7, 10])

In [67]:
np.percentile(a,100)

np.float64(10.0)

In [68]:
np.percentile(a,0)

np.float64(1.0)

In [69]:
np.percentile(a,50)

np.float64(3.5)

In [70]:
# ===================np.histogram=====================
a = np.array([5,15,9,17,39])
np.histogram(a,bins=[0,10,20,30,40,50])

(array([2, 2, 0, 1, 0]), array([ 0, 10, 20, 30, 40, 50]))

In [71]:
# ===================np.corrcoef==================
slary = np.array([2000,3000,4000,5000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(slary,experience)

array([[ 1.        , -0.16124754],
       [-0.16124754,  1.        ]])

In [72]:
#  ======================np.isni=================
a

array([ 5, 15,  9, 17, 39])

In [73]:
np.isin(a,5)

array([ True, False, False, False, False])

In [74]:
item = [5,15]
np.isin(a,item)

array([ True,  True, False, False, False])

In [75]:
# ===================np.flip==================
a

array([ 5, 15,  9, 17, 39])

In [76]:
np.flip(a)

array([39, 17,  9, 15,  5])

In [77]:
b

array([[64, 16, 19, 21, 29, 53,  6, 28, 65, 71],
       [ 4,  5, 63, 12, 48, 76, 12, 71, 63, 62],
       [ 8, 31, 82, 78, 90,  2, 36,  6, 55, 87],
       [16, 75,  1, 55, 99, 84, 20, 73, 73, 41],
       [77, 79, 43, 91, 99, 55, 97, 84, 80, 51]])

In [78]:
np.flip(b)

array([[51, 80, 84, 97, 55, 99, 91, 43, 79, 77],
       [41, 73, 73, 20, 84, 99, 55,  1, 75, 16],
       [87, 55,  6, 36,  2, 90, 78, 82, 31,  8],
       [62, 63, 71, 12, 76, 48, 12, 63,  5,  4],
       [71, 65, 28,  6, 53, 29, 21, 19, 16, 64]])

In [79]:
np.flip(b ,axis = 0)

array([[77, 79, 43, 91, 99, 55, 97, 84, 80, 51],
       [16, 75,  1, 55, 99, 84, 20, 73, 73, 41],
       [ 8, 31, 82, 78, 90,  2, 36,  6, 55, 87],
       [ 4,  5, 63, 12, 48, 76, 12, 71, 63, 62],
       [64, 16, 19, 21, 29, 53,  6, 28, 65, 71]])

In [80]:
# ====================np.put============
a

array([ 5, 15,  9, 17, 39])

In [82]:
np.put(a,[0,1],[200,400])
a

array([200, 400,   9,  17,  39])

In [83]:
# =============================np.delete====================
a

array([200, 400,   9,  17,  39])

In [86]:
np.delete(a,0)

array([200, 400,   9,  17,  39])

In [90]:
# ==============================set function===========================
m = np.array([1,2,3,4,5,6,7])

n = np.array([1,2,3,4,5,6,7,8,9])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.intersect1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [92]:
np.setdiff1d(m,n)

array([], dtype=int64)

In [93]:
np.setdiff1d(n,m)

array([8, 9])

In [94]:
np.setxor1d(m,n)

array([8, 9])

In [97]:
np.in1d(m,2)

/tmp/ipykernel_2141/595628413.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,2)


array([False,  True, False, False, False, False, False])

In [98]:
# =========================np.clip==============================
a

array([200, 400,   9,  17,  39])

In [100]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 25, 39])