<a href="https://colab.research.google.com/github/itsyogi01/PYTHON--45DAYS-PRACTICE/blob/main/day7_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2d
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3d
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
d = np.array([1,2,3],dtype =float)
print(d)

[1. 2. 3.]


In [11]:
# np.arange
np.arange(1,11)

array([1, 3, 5, 7, 9])

In [12]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
# np.arange
np.arange(1,11).reshape(5,2)
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# np.random.random
np.random.random((3,4))

array([[0.48841221, 0.45301925, 0.14284122, 0.69134897],
       [0.91309849, 0.63839754, 0.63545208, 0.51129976],
       [0.86600714, 0.184589  , 0.60041549, 0.79508511]])

In [21]:
# np.linespace
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
# np.identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# -----------------------numpy attribute----------------------
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


1

In [34]:
# ndim
a1.ndim

3

In [32]:
a2.ndim

2

In [33]:
a3.ndim

3

In [38]:
# shape
print(a1.shape)
a1

(10,)
(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [39]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
# size
a1.size

12

In [43]:
a2.size

12

In [44]:
a3.size

8

In [45]:
# ITEM SIZE
a1.itemsize

8

In [46]:
a2.itemsize

8

In [47]:
a3.itemsize

8

In [52]:
a4 = np.arange(5,dtype = np.int32)
print(a4)
a4.itemsize
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)

[0 1 2 3 4]
int64
float64
int64
int32


In [54]:
# astype
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [55]:
# ------------------Array operation------------
# arthmetic operater
a5 = np.arange(12).reshape(3,4)
a6 = np.arange(12,24).reshape(3,4)

In [60]:
print(a5)
a5*2
a5**2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [64]:
# relational operater
a5>4


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [65]:
a6 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [66]:
# vector operation
# arithmetic
a5+a6

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [68]:
# max/min/sum/prod
np.max(a1)
np.min(a5)

np.int64(0)

In [69]:
np.min(a5)

np.int64(0)

In [70]:
np.sum(a1)

np.int64(45)

In [71]:
np.prod(a1)

np.int64(0)

In [74]:
np.max(a2,axis=0)


array([ 8.,  9., 10., 11.])

In [75]:
np.mean(a1)

np.float64(4.5)

In [77]:
np.median(a2)

np.float64(5.5)

In [80]:
np.std(a2,axis =1)

array([1.11803399, 1.11803399, 1.11803399])

In [81]:
np.sin(a1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [90]:
a7 = np.arange(12).reshape(3,4)
a8 = np.arange(12,24).reshape(4,3)
np.dot(a7,a8)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [93]:
# log and exponents
np.exp(a1)
np.log(a1)

/tmp/ipykernel_3634/3962210963.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [104]:
# round/floor/ceil
np.random.random((2,3))*100

array([[92.22891599,  4.49464961, 99.40309725],
       [42.46032352, 17.24515632, 98.5212998 ]])

In [105]:
np.round(np.random.random((2,3))*100)

array([[31., 28., 32.],
       [33., 43., 93.]])

In [106]:
np.floor(np.random.random((2,3))*100)

array([[34., 30., 61.],
       [63., 18., 54.]])

In [107]:
np.ceil(np.random.random((2,3))*100)

array([[60., 52., 11.],
       [37., 41., 46.]])

In [138]:
# -----------------indexing and slicing---------------
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [128]:
a1[0]
# a1[-1]

np.int64(0)

In [143]:
print(a2)
a2[1,2]
a2[2,3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(11)

In [148]:
a3
a3[1,0,1]
print(a3[0,0,0])
print(a3[1,1,0])

0
6


In [153]:
# slicing
a1
print(a1[2:5:2])
print(a1[2:5])

[2 4]
[2 3 4]


In [171]:
a2




array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [165]:
a2[0,:]

array([0, 1, 2, 3])

In [164]:
a2[:,2]

array([ 2,  6, 10])

In [166]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [167]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [169]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [172]:
a2[1,::3]

array([4, 7])

In [174]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [178]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [179]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [181]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [182]:
a3[0,1,:]

array([3, 4, 5])

In [184]:
a3[1,:,1]

array([10, 13, 16])

In [185]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [188]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [190]:
# ITERATING
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [191]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [192]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [193]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [194]:
# Reshaping/transpose/ravel
# traspose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [198]:
# ravel
a2.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [200]:
# -----------------stacking-----------------
# horizontal
a8 = np.arange(12).reshape(3,4)
a9 = np.arange(12,24).reshape(3,4)
np.hstack((a8,a9))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [201]:
np.hstack((a8,a9,a8))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [203]:
# vertical
np.vstack((a8,a9))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [205]:
# spliting
a8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [206]:
np.hsplit(a8,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [211]:
np.hsplit(a8,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [212]:
# vertical splitting
a8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [213]:
np.vsplit(a8,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]